### PR TITLE
Add websocket

### PR DESCRIPTION
**Pull request by dfarr**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://review-ninja-staging.cfapps.io/dfarr/foo/pull/1" target="_blank">ReviewNinja

**Comment by dfarr** [comment]
:-1:

**Comment by dfarr** [comment]
:+1:

**Comment by dfarr** [comment]
-1

**Comment by dfarr** [comment]
-1

**Comment by dfarr** [comment]
:+1:

**Comment by dfarr** [comment]
```js
var a = 3;
```

**Pull request merged**
